### ISSUE TITLE
Plugin Install Failed Without an Alert

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/gui#36]
Reproduction steps.
1. click on install my-q plugin as soon the installation process starts
2. manually refresh the page
3. only bridge was generated, but plugin not installed

Expected behavior
installation should work in the background even if the window is closed or refreshed

Here is my debug log
```
17/03/2021, 20:57:46 myQ Bridge starting
17/03/2021, 20:58:01 myQ Bridge WARNING No plugins installed.
17/03/2021, 20:58:01 myQ Bridge Preparing Advertiser for 'myQ Bridge 0929' using bonjour-hap backend!
17/03/2021, 20:58:01 myQ Bridge Starting to advertise 'myQ Bridge 0929' using bonjour-hap backend!
17/03/2021, 20:58:01 myQ Bridge Bridge is running on port 53826.

application | distribution | package_manager | version | latest  | upgraded | init_system | running
---------------------------------------------------------------------------------------------------
cli         | raspbian     | apt-get         | 4.0.14  | 4.0.14  | true     |             |        
gui         | raspbian     | apt-get         | 4.0.30  | 4.0.30  | true     |             |        
hoobsd      | raspbian     | apt-get         | 4.0.32  | 4.0.32  | true     | systemd     | true   
node        | raspbian     | apt-get         | 14.16.0 | 14.16.0 | true     |             |        
```

**Comment by mkellsy** [comment]
This is a 2 step process.
1. Create bridge
2. install plugin

If the create bridge command is sent, it will still work in the background, however if a user refreshes, essentially stopping the second install call, the plugin will never be installed.

These actions didn't break the system, and it acted as expected. The worst thing the user will have to do is click install again, but select the bridge that was created in the first attempt.

See in the CLI, you must first create a bridge, then install a plugin on that bridge. The GUI is just an interface on top of the CLI.

If you install to an existing bridge, the install command is instantly sent.

I am marking this a s Wont Fix. Because no real damage was created.
