### ISSUE TITLE
Redirect Back to Plugin Page for Plugins that Do Not have a Schema

### ISSUE THREAD

**Issue by EddieDSuza** [hoobs-org/gui#73]
https://user-images.githubusercontent.com/52710883/115257210-3bcb7f80-a106-11eb-8777-4dc416109614.mov

The below plugins do not support config.schema and when clicking on configuration - the page takes you the hub settings - 

```
1. > homebridge-plex
2. > homebridge-synology
3. > homebridge-soundtouch-platform
```

Attached video for reference

**Comment by mkellsy** [comment]
Plugins that don't have a schema should not redirect to the config screen. They also shouldn't have a config button either.

**Comment by mkellsy** [comment]
I thought about this one.

Redirecting to the config screen after a plugin install kina' makes sense.
For users that don't know what the next step is, it helps.

However, sometimes it can be "too helpful", especially if I don't have all the info yet. Redirecting back to the plugin page with updated buttons, is a more stable option. Because we know the plugin page is always there, and the screen already has all the info needed. Not all plugins have a config schema. So redirecting adds unnecessary un-stability, plus on a plugin install, I don't know of or how the schema is delivered (some have overrides).

I think it is a fair ask to change the work flow to this;

1. Install a plugin
2. Click Configuration (If it is there)
3. Configure plugin.

If there is no Configuration button, this plugin needs to be configured manually, go to the Config -> Advanced screen.

This change is done in
GUI 4.0.44
Desktop 4.0.14

**Comment by EddieDSuza** [comment]
The HOOBS 3 does have the configuration box for non schema plugins and this allows our novice users not to mess anything in the advanced section.
The addition of the configuration box will assist our users to only include .json information where required.

**Comment by mkellsy** [comment]
Or if it becomes an issue, we can just add a schema to the plugins site. Yes, even for plugins that don't have one.
